import { HR_EMPLOYEE_CARDS_TYPE } from "../types/HrEmployee.type";

export const dummyEmployeeCards: HR_EMPLOYEE_CARDS_TYPE[] = [
  {
    id: "EMP001",
    name: "John Doe",
    phone: "+1-555-1234",
    email: "john.doe@example.com",
    joiningDate: "2020-05-15",
    dateofLastIncrement: "2023-04-01",
    designation: "Software Engineer",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    department: "Engineering",
    currentSalary: 75000,
    onClick: () => console.log("Clicked on John Doe"),
  },
  {
    id: "EMP002",
    name: "Jane Smith",
    phone: "+1-555-5678",
    email: "jane.smith@example.com",
    joiningDate: "2019-08-22",
    dateofLastIncrement: "2023-03-15",
    designation: "Product Manager",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    department: "Product",
    currentSalary: 92000,
    onClick: () => console.log("Clicked on Jane Smith"),
  },
  {
    id: "EMP003",
    name: "Michael Johnson",
    phone: "+1-555-9101",
    email: "michael.johnson@example.com",
    joiningDate: "2018-01-10",
    dateofLastIncrement: "2022-11-20",
    designation: "HR Specialist",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    department: "Human Resources",
    currentSalary: 64000,
    onClick: () => console.log("Clicked on Michael Johnson"),
  },
  {
    id: "EMP004",
    name: "Emily Davis",
    phone: "+1-555-2345",
    email: "emily.davis@example.com",
    joiningDate: "2021-07-30",
    dateofLastIncrement: "2023-06-10",
    designation: "UI/UX Designer",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    department: "Design",
    currentSalary: 68000,
    onClick: () => console.log("Clicked on Emily Davis"),
  },
  {
    id: "EMP005",
    name: "Robert Brown",
    phone: "+1-555-6789",
    email: "robert.brown@example.com",
    joiningDate: "2017-03-12",
    dateofLastIncrement: "2023-01-05",
    designation: "Senior Developer",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    department: "Engineering",
    currentSalary: 105000,
    onClick: () => console.log("Clicked on Robert Brown"),
  },
  {
    id: "EMP006",
    name: "Olivia Wilson",
    phone: "+1-555-1110",
    email: "olivia.wilson@example.com",
    joiningDate: "2022-02-18",
    dateofLastIncrement: "2023-05-20",
    designation: "Marketing Specialist",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    department: "Marketing",
    currentSalary: 58000,
    onClick: () => console.log("Clicked on Olivia Wilson"),
  },
  {
    id: "EMP007",
    name: "William Martinez",
    phone: "+1-555-2221",
    email: "william.martinez@example.com",
    joiningDate: "2016-11-05",
    dateofLastIncrement: "2023-02-28",
    designation: "Finance Analyst",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
    department: "Finance",
    currentSalary: 72000,
    onClick: () => console.log("Clicked on William Martinez"),
  },
  {
    id: "EMP008",
    name: "Sophia Anderson",
    phone: "+1-555-3332",
    email: "sophia.anderson@example.com",
    joiningDate: "2020-04-23",
    dateofLastIncrement: "2023-07-01",
    designation: "Content Writer",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    department: "Marketing",
    currentSalary: 50000,
    onClick: () => console.log("Clicked on Sophia Anderson"),
  },
  {
    id: "EMP009",
    name: "James Thomas",
    phone: "+1-555-4443",
    email: "james.thomas@example.com",
    joiningDate: "2015-09-14",
    dateofLastIncrement: "2022-12-15",
    designation: "Senior Accountant",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    department: "Finance",
    currentSalary: 95000,
    onClick: () => console.log("Clicked on James Thomas"),
  },
  {
    id: "EMP010",
    name: "Isabella Taylor",
    phone: "+1-555-5554",
    email: "isabella.taylor@example.com",
    joiningDate: "2021-03-29",
    dateofLastIncrement: "2023-08-05",
    designation: "Recruiter",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    department: "Human Resources",
    currentSalary: 60000,
    onClick: () => console.log("Clicked on Isabella Taylor"),
  },
  {
    id: "EMP011",
    name: "Benjamin Lee",
    phone: "+1-555-6665",
    email: "benjamin.lee@example.com",
    joiningDate: "2019-07-12",
    dateofLastIncrement: "2023-04-30",
    designation: "Data Analyst",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    department: "Engineering",
    currentSalary: 78000,
    onClick: () => console.log("Clicked on Benjamin Lee"),
  },
  {
    id: "EMP012",
    name: "Mia Harris",
    phone: "+1-555-7776",
    email: "mia.harris@example.com",
    joiningDate: "2018-06-08",
    dateofLastIncrement: "2022-10-12",
    designation: "Graphic Designer",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    department: "Design",
    currentSalary: 67000,
    onClick: () => console.log("Clicked on Mia Harris"),
  },
  {
    id: "EMP013",
    name: "Alexander Walker",
    phone: "+1-555-8887",
    email: "alexander.walker@example.com",
    joiningDate: "2017-01-17",
    dateofLastIncrement: "2023-01-30",
    designation: "Project Manager",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
    department: "Product",
    currentSalary: 98000,
    onClick: () => console.log("Clicked on Alexander Walker"),
  },
  {
    id: "EMP014",
    name: "Charlotte Hall",
    phone: "+1-555-9998",
    email: "charlotte.hall@example.com",
    joiningDate: "2022-09-26",
    dateofLastIncrement: "2023-09-15",
    designation: "Business Analyst",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
    department: "Finance",
    currentSalary: 71000,
    onClick: () => console.log("Clicked on Charlotte Hall"),
  },
  {
    id: "EMP015",
    name: "Daniel Allen",
    phone: "+1-555-0009",
    email: "daniel.allen@example.com",
    joiningDate: "2016-10-03",
    dateofLastIncrement: "2023-03-22",
    designation: "DevOps Engineer",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
    department: "Engineering",
    currentSalary: 88000,
    onClick: () => console.log("Clicked on Daniel Allen"),
  },
  {
    id: "EMP016",
    name: "Amelia Young",
    phone: "+1-555-1010",
    email: "amelia.young@example.com",
    joiningDate: "2021-05-11",
    dateofLastIncrement: "2023-06-18",
    designation: "QA Engineer",
    image: "https://randomuser.me/api/portraits/women/16.jpg",
    department: "Engineering",
    currentSalary: 70000,
    onClick: () => console.log("Clicked on Amelia Young"),
  },
  {
    id: "EMP017",
    name: "Matthew Hernandez",
    phone: "+1-555-2021",
    email: "matthew.hernandez@example.com",
    joiningDate: "2019-11-25",
    dateofLastIncrement: "2023-04-10",
    designation: "Frontend Developer",
    image: "https://randomuser.me/api/portraits/men/17.jpg",
    department: "Engineering",
    currentSalary: 76000,
    onClick: () => console.log("Clicked on Matthew Hernandez"),
  },
  {
    id: "EMP018",
    name: "Harper King",
    phone: "+1-555-3032",
    email: "harper.king@example.com",
    joiningDate: "2020-08-14",
    dateofLastIncrement: "2023-05-05",
    designation: "HR Assistant",
    image: "https://randomuser.me/api/portraits/women/18.jpg",
    department: "Human Resources",
    currentSalary: 55000,
    onClick: () => console.log("Clicked on Harper King"),
  },
  {
    id: "EMP019",
    name: "Ethan Wright",
    phone: "+1-555-4043",
    email: "ethan.wright@example.com",
    joiningDate: "2018-02-20",
    dateofLastIncrement: "2023-02-11",
    designation: "Backend Developer",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
    department: "Engineering",
    currentSalary: 82000,
    onClick: () => console.log("Clicked on Ethan Wright"),
  },
  {
    id: "EMP020",
    name: "Abigail Lopez",
    phone: "+1-555-5054",
    email: "abigail.lopez@example.com",
    joiningDate: "2021-12-07",
    dateofLastIncrement: "2023-07-20",
    designation: "Social Media Manager",
    image: "https://randomuser.me/api/portraits/women/20.jpg",
    department: "Marketing",
    currentSalary: 63000,
    onClick: () => console.log("Clicked on Abigail Lopez"),
  },
  {
    id: "EMP021",
    name: "Logan Scott",
    phone: "+1-555-6065",
    email: "logan.scott@example.com",
    joiningDate: "2019-04-18",
    dateofLastIncrement: "2023-03-28",
    designation: "Technical Lead",
    image: "https://randomuser.me/api/portraits/men/21.jpg",
    department: "Engineering",
    currentSalary: 110000,
    onClick: () => console.log("Clicked on Logan Scott"),
  },
  {
    id: "EMP022",
    name: "Ella Green",
    phone: "+1-555-7076",
    email: "ella.green@example.com",
    joiningDate: "2022-03-04",
    dateofLastIncrement: "2023-08-01",
    designation: "Marketing Coordinator",
    image: "https://randomuser.me/api/portraits/women/22.jpg",
    department: "Marketing",
    currentSalary: 54000,
    onClick: () => console.log("Clicked on Ella Green"),
  },
  {
    id: "EMP023",
    name: "Joseph Adams",
    phone: "+1-555-8087",
    email: "joseph.adams@example.com",
    joiningDate: "2017-07-29",
    dateofLastIncrement: "2023-01-12",
    designation: "Full Stack Developer",
    image: "https://randomuser.me/api/portraits/men/23.jpg",
    department: "Engineering",
    currentSalary: 90000,
    onClick: () => console.log("Clicked on Joseph Adams"),
  },
  {
    id: "EMP024",
    name: "Grace Nelson",
    phone: "+1-555-9098",
    email: "grace.nelson@example.com",
    joiningDate: "2020-10-21",
    dateofLastIncrement: "2023-05-22",
    designation: "UI Designer",
    image: "https://randomuser.me/api/portraits/women/24.jpg",
    department: "Design",
    currentSalary: 69000,
    onClick: () => console.log("Clicked on Grace Nelson"),
  },
  {
    id: "EMP025",
    name: "David Carter",
    phone: "+1-555-0109",
    email: "david.carter@example.com",
    joiningDate: "2018-05-16",
    dateofLastIncrement: "2023-03-04",
    designation: "System Administrator",
    image: "https://randomuser.me/api/portraits/men/25.jpg",
    department: "IT Support",
    currentSalary: 80000,
    onClick: () => console.log("Clicked on David Carter"),
  },
  {
    id: "EMP026",
    name: "Victoria Mitchell",
    phone: "+1-555-1112",
    email: "victoria.mitchell@example.com",
    joiningDate: "2021-09-09",
    dateofLastIncrement: "2023-06-15",
    designation: "Recruitment Specialist",
    image: "https://randomuser.me/api/portraits/women/26.jpg",
    department: "Human Resources",
    currentSalary: 61000,
    onClick: () => console.log("Clicked on Victoria Mitchell"),
  },
  {
    id: "EMP027",
    name: "Samuel Perez",
    phone: "+1-555-2123",
    email: "samuel.perez@example.com",
    joiningDate: "2019-02-27",
    dateofLastIncrement: "2023-02-07",
    designation: "Tech Support Engineer",
    image: "https://randomuser.me/api/portraits/men/27.jpg",
    department: "IT Support",
    currentSalary: 72000,
    onClick: () => console.log("Clicked on Samuel Perez"),
  },
  {
    id: "EMP028",
    name: "Aria Roberts",
    phone: "+1-555-3134",
    email: "aria.roberts@example.com",
    joiningDate: "2020-01-13",
    dateofLastIncrement: "2023-04-17",
    designation: "Copywriter",
    image: "https://randomuser.me/api/portraits/women/28.jpg",
    department: "Marketing",
    currentSalary: 57000,
    onClick: () => console.log("Clicked on Aria Roberts"),
  },
  {
    id: "EMP029",
    name: "Christopher Turner",
    phone: "+1-555-4145",
    email: "christopher.turner@example.com",
    joiningDate: "2016-08-03",
    dateofLastIncrement: "2023-01-19",
    designation: "Network Engineer",
    image: "https://randomuser.me/api/portraits/men/29.jpg",
    department: "IT Support",
    currentSalary: 83000,
    onClick: () => console.log("Clicked on Christopher Turner"),
  },
  {
    id: "EMP030",
    name: "Chloe Phillips",
    phone: "+1-555-5156",
    email: "chloe.phillips@example.com",
    joiningDate: "2022-06-01",
    dateofLastIncrement: "2023-07-28",
    designation: "HR Manager",
    image: "https://randomuser.me/api/portraits/women/30.jpg",
    department: "Human Resources",
    currentSalary: 75000,
    onClick: () => console.log("Clicked on Chloe Phillips"),
  },
  {
    id: "EMP031",
    name: "Nathan Campbell",
    phone: "+1-555-6167",
    email: "nathan.campbell@example.com",
    joiningDate: "2017-04-19",
    dateofLastIncrement: "2023-03-15",
    designation: "Senior Architect",
    image: "https://randomuser.me/api/portraits/men/31.jpg",
    department: "Engineering",
    currentSalary: 115000,
    onClick: () => console.log("Clicked on Nathan Campbell"),
  },
  {
    id: "EMP032",
    name: "Lily Parker",
    phone: "+1-555-7178",
    email: "lily.parker@example.com",
    joiningDate: "2021-08-25",
    dateofLastIncrement: "2023-05-08",
    designation: "SEO Specialist",
    image: "https://randomuser.me/api/portraits/women/32.jpg",
    department: "Marketing",
    currentSalary: 60000,
    onClick: () => console.log("Clicked on Lily Parker"),
  },
  {
    id: "EMP033",
    name: "Andrew Evans",
    phone: "+1-555-8189",
    email: "andrew.evans@example.com",
    joiningDate: "2019-12-15",
    dateofLastIncrement: "2023-04-02",
    designation: "Database Administrator",
    image: "https://randomuser.me/api/portraits/men/33.jpg",
    department: "IT Support",
    currentSalary: 87000,
    onClick: () => console.log("Clicked on Lily Parker"),
  },
];
